theme: jekyll-theme-tactile
github:
  clone_url: 
  issues_url:
  releases_url:
  repository_nwo:
  repository_url: xcodereleases/xcodereleases.com
  tar_url:
  owner_gravatar_url:
  public: false
  owner_name: Xcode Releases
  owner_url: https://twitter.com/xcodereleases

repository: xcodereleases/xcodereleases.com